### ISSUE TITLE
etcdctl member list shows different ETCD host of cluster everytime

### ISSUE THREAD

**Issue by git1988** [viiyu/memo#5]
I just restored ETCD from backups.
etcd services are started in all nodes and restore is also successful.
But running etcdctl member list and cluster health gives only 1 server name at a time.

**Comment by git1988** [comment]
How can we fix this Issue ?

**Comment by viiyu** [comment]
sry, this project is just a notebook of commands used in my work. I will close this issue.

In your case, I think you should add '--endpoints' to point out members of your 'member list' cmd. 

> How can we fix this Issue ?
